server:
  port: 8855
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./blog_app;
  jpa:
    hibernate:
      ddl-auto: create # in prod, use update, NOT create
    show-sql: true
  security:
    user:
      name: Bhuvi
      password: 1234
